[package]
name = "visualiser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
concrete-fft = "0.3.0"

[dependencies.raylib-ffi]
version = "5.0.0"
git = "https://github.com/ewpratten/raylib-ffi"
